# flutter pub get
# flutter gen-l10n
# flutter pub run flutter_launcher_icons
# flutter build apk --release

name: simple_kiosk_software
description: "简易医疗亭/simple kiosk software"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  flutter_sizer: ^1.0.5
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  dio: ^5.7.0
  equatable: ^2.0.5
  image: ^4.2.0
  intl: any
  logger: ^2.4.0
  responsive_framework: ^0.2.0
  shared_preferences: ^2.3.1
  video_player: ^2.9.2
  buttons_tabbar: ^1.3.13
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^10.2.0
  flutter_esc_pos_utils: ^1.0.1
  device_info_plus: ^9.1.2
  #fluttertoast: ^8.2.6
  tdesign_flutter: ^0.1.7
  camera: ^0.10.6
  audioplayers: ^6.1.0
  #record: ^5.2.0
  path_provider: ^2.1.5
  web_socket_channel: ^2.4.0
  hmssdk_flutter: ^1.10.3
  easy_image_viewer: ^1.4.0
  connectivity_plus: ^5.0.2
  package_info_plus: ^8.1.1
  re_editor: ^0.6.0
  re_highlight: ^0.0.3
  firebase_core: ^3.7.0
  firebase_database: ^11.1.5
  libserialport: ^0.3.0+1
#  flutter_devices_sdk: # 包名
#      git:
#        #url: https://github.com/Medlyves-Pte-Ltd/flutter_devices_sdk.git
#        url: https://gitee.com/caipingan456/flutter_devices_sdk.git
#        ref: docking_station # 分支
  medlyves_mobile_components:
          git:
            url: https://gitee.com/caipingan456/medlyves_mobile_components.git
            ref: enhance-video-quality # 分支
#            url: git@github.com:Medlyves-Pte-Ltd/medlyves_mobile_components.git
#            ref: 9adfd05

  flutter_devices_sdk:
    path: D:\Android\Projects\flutter\flutter_devices_sdk

## 运行生成图标命令
## flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  image_path: "assets/images/Medlyves_logo_only.png"
  min_sdk_android: 26 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
#    - assets/audios/
    - assets/images/
#    - assets/videos/
#    - assets/videos/en/
#    - assets/videos/zh/
#    - assets/videos/ta/
#    - assets/videos/ms/
#    - assets/videos/th/
#    - assets/configs/
#    - assets/configs/devices/
